name: C/C++ CI

on: [push, pull_request]

jobs:
  llvm10:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: install ninja
      run: sudo apt-get -y install ninja-build
    - name: install apt.llvm.org repo
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 10
    - name: install clang-dev
      run: sudo apt-get -y install llvm-10-dev libclang-10-dev
    - name: build
      run: mkdir build && cd build && cmake .. && make
  
  llvm11:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: install ninja
      run: sudo apt-get -y install ninja-build
    - name: install apt.llvm.org repo
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 11
    - name: install clang-dev
      run: sudo apt-get -y install llvm-11-dev libclang-11-dev
    - name: build
      run: mkdir build && cd build && cmake .. && make
